"""Dataset loader for graph bundles stored on disk."""

from __future__ import annotations

from pathlib import Path

import numpy as np

from core.graph import Graph
from core.registry import register_dataset
from data.base import Dataset
from data.io import load_graph_bundle


@register_dataset("serialized_graph")
class SerializedGraphDataset(Dataset):
    """Load a graph bundle generated by the dataset scripts."""

    def __init__(self, path: str, num_clusters: int | None = None) -> None:
        self.path = Path(path)
        self._num_clusters_override = num_clusters

    def load(self) -> tuple[Graph, np.ndarray]:
        graph, target, inferred_num_clusters = load_graph_bundle(self.path)
        self._inferred_num_clusters = inferred_num_clusters
        return graph, target

    @property
    def num_clusters(self) -> int:
        if self._num_clusters_override is not None:
            return int(self._num_clusters_override)
        if hasattr(self, "_inferred_num_clusters"):
            return int(self._inferred_num_clusters)
        _, _, inferred_num_clusters = load_graph_bundle(self.path)
        self._inferred_num_clusters = inferred_num_clusters
        return int(inferred_num_clusters)
